###
POST   http://localhost:4004/odata/v4/grocery/Customers
Content-Type: application/json

{
  "ID":"529",
    "name": "Devender Maram",
    "email": "sasank@example.com",
    "address": "lorem epsum",
    "phoneNumber": "+91 9849801762"
}

###
POST   http://localhost:4004/odata/v4/grocery/Orders
Content-Type: application/json

{

      "ID":"1011",
      "orderDate": "2025-03-26",
      "totalAmount": 0,
      "customer_ID": "529"
}

###
POST   http://localhost:4004/odata/v4/grocery/OrderItems
Content-Type: application/json

{
  "quantity": 100,
  "itemPrice": 0,
  "totalItemPrice": 0,
  "order_ID": "1011",
  "item_ID": "6db536d1-06db-4783-97b6-802b18905111"
}




###
POST   http://localhost:4004/odata/v4/grocery/Items
Content-Type: application/json

 {
      
      "name": "Apples",
      "price": 20,
      "description": "Fresh red apples",
      "stockQuantity": 100
    }


###
GET http://localhost:4004/odata/v4/grocery/Customers


###
GET http://localhost:4004/odata/v4/grocery/Orders


###
GET http://localhost:4004/odata/v4/grocery/OrderItems


###
GET http://localhost:4004/odata/v4/grocery/Items